# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\controlPanel\controlpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.led_time_on = QtWidgets.QTimeEdit(self.centralwidget)
        self.led_time_on.setGeometry(QtCore.QRect(270, 90, 181, 71))
        self.led_time_on.setObjectName("led_time_on")
        self.apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.apply_button.setGeometry(QtCore.QRect(570, 350, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.apply_button.setFont(font)
        self.apply_button.setStyleSheet("background-color: rgb(42, 96, 73);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30px;")
        self.apply_button.setObjectName("apply_button")
        self.water_time_off = QtWidgets.QTimeEdit(self.centralwidget)
        self.water_time_off.setGeometry(QtCore.QRect(500, 220, 181, 71))
        self.water_time_off.setObjectName("water_time_off")
        self.water_time_on = QtWidgets.QTimeEdit(self.centralwidget)
        self.water_time_on.setGeometry(QtCore.QRect(270, 220, 181, 71))
        self.water_time_on.setObjectName("water_time_on")
        self.led_time_off = QtWidgets.QTimeEdit(self.centralwidget)
        self.led_time_off.setGeometry(QtCore.QRect(500, 90, 181, 71))
        self.led_time_off.setObjectName("led_time_off")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 120, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 250, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apply_button.setText(_translate("MainWindow", "Apply"))
        self.label.setText(_translate("MainWindow", "~"))
        self.label_2.setText(_translate("MainWindow", "~"))
        self.label_3.setText(_translate("MainWindow", "LED"))
        self.label_4.setText(_translate("MainWindow", "Water"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
